### ISSUE TITLE
Using pipeline parameters for material definition

### ISSUE THREAD

**Issue by ashishreddyv** [TWChennai/gocd-git-path-material-plugin#29]
I'm trying to use pipeline parameters for defining the material with git path material plugin. Here's how my definition looks for a material:
```
my_pipeline:
  group: build
  parameters:
    git-url: git@github.com:test/test-gocd.git
    project-path: sub_pj1
 materials:
   dev-material:
     plugin_configuration:
       id: git-path
     options:
       url: "#{git-url}"
       path: "#{project-path}"
       branch: develop
     destination: my_project
```
I see a 128 error code when GoCD is trying to parse this pipeline config.

The default git material that gocd has allows this type of material declaration but not the git path material. 
This is particularly useful for projects that have huge number of microservices in which we can use yaml aliases for the materials and just define the overriding parameters.
